[package]
name = "FluorateGL"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
name = "fluorategl"

[[example]]
name = "glslang_suite"
path = "tests/glsl/glslang_suite.rs"

[dependencies]
bytemuck = { version = "1", default-features = false }
ctor = "1.0.9"
glslang = "0.8.1"
libc = "0.2.186"
log = "0.4.33"
regex = "1"
shaderc = { version = "0.10.1", features = ["build-from-source"] }
spirv-cross2 = { version = "0.7.1", default-features = false, features = ["glsl","cpp"] }

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 8

