//! GL stub 导出（生成器输出 tools/gen_stub_exports.py，勿手改）
//!
//! 阶段 2/3：GL 4.x + 扩展后缀函数批量 stub（GLES 无对应或超出北极星 3.3 范围）。
//! stub 语义：存在不崩溃（LWJGL 绑定 null 防护），调用 no-op + debug 日志，
//! 返回类型默认值（0/null/()）。对齐 MobileGlues STUB 策略。

macro_rules! stub_fn {
    ($name:ident, $ret:ty, ($($arg:ident: $ty:ty),*)) => {
        #[unsafe(no_mangle)]
        #[allow(non_snake_case, unused_variables)]
        pub extern "C" fn $name($($arg: $ty),*) -> $ret {
            log::debug!("[FluorateGL] stub {}", stringify!($name));
            <$ret>::default()
        }
    };
}

macro_rules! passthrough_alias {
    ($name:ident, $target:path, $ret:ty, ($($arg:ident: $ty:ty),*)) => {
        #[unsafe(no_mangle)]
        #[allow(non_snake_case, unused_variables)]
        pub extern "C" fn $name($($arg: $ty),*) -> $ret {
            $target($($arg),*)
        }
    };
}

stub_fn!(glActiveProgramEXT, (), (program: u32));
stub_fn!(glActiveShaderProgram, (), (pipeline: u32, program: u32));
stub_fn!(glApplyFramebufferAttachmentCMAAINTEL, (), ());
stub_fn!(glAreTexturesResident, u8, (n: i32, textures: *const u32, residences: *mut u8));
stub_fn!(glBindBuffersBase, (), (target: u32, first: u32, count: i32, buffers: *const u32));
stub_fn!(glBindBuffersRange, (), (target: u32, first: u32, count: i32, buffers: *const u32, offsets: *const isize, sizes: *const isize));
stub_fn!(glBindFragDataLocationEXT, (), (program: u32, colorNumber: u32, name: *const std::ffi::c_char));
// glBindImageTexture 已由 drawing.rs 真实导出（D4-3：MG drawing.cpp 透传）——
// 生成器下次运行会经 nm 自动排除（load_ours），勿手动加回。
stub_fn!(glBindImageTextures, (), (first: u32, count: i32, textures: *const u32));
stub_fn!(glBindMultiTextureEXT, (), (texunit: u32, target: u32, texture: u32));
stub_fn!(glBindProgramPipeline, (), (pipeline: u32));
stub_fn!(glBindSamplers, (), (first: u32, count: i32, samplers: *const u32));
stub_fn!(glBindShadingRateImageNV, (), (texture: u32));
stub_fn!(glBindTextureUnit, (), (unit: u32, texture: u32));
stub_fn!(glBindTextures, (), (first: u32, count: i32, textures: *const u32));
stub_fn!(glBindVertexBuffers, (), (first: u32, count: i32, buffers: *const u32, offsets: *const isize, strides: *const i32));
stub_fn!(glBlendBarrierKHR, (), ());
stub_fn!(glBlendBarrierNV, (), ());
stub_fn!(glBlendParameteriNV, (), (pname: u32, value: i32));
stub_fn!(glBlitNamedFramebuffer, (), (readFramebuffer: u32, drawFramebuffer: u32, srcX0: i32, srcY0: i32, srcX1: i32, srcY1: i32, dstX0: i32, dstY0: i32, dstX1: i32, dstY1: i32, mask: u32, filter: u32));
stub_fn!(glBufferAddressRangeNV, (), (pname: u32, index: u32, address: u64, length: isize));
stub_fn!(glBufferAttachMemoryNV, (), (target: u32, memory: u32, offset: u64));
stub_fn!(glBufferPageCommitmentARB, (), (target: u32, offset: isize, size: isize, commit: u8));
stub_fn!(glBufferPageCommitmentMemNV, (), (target: u32, offset: isize, size: isize, memory: u32, memOffset: u64, commit: u8));
stub_fn!(glCallCommandListNV, (), (list: u32));
stub_fn!(glCheckNamedFramebufferStatus, u32, (framebuffer: u32, target: u32));
stub_fn!(glCheckNamedFramebufferStatusEXT, u32, (framebuffer: u32, target: u32));
stub_fn!(glClearBufferData, (), (target: u32, internalformat: u32, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearBufferSubData, (), (target: u32, internalformat: u32, offset: isize, size: isize, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearDepthdNV, (), (depth: f64));
stub_fn!(glClearDepthf, (), (d: f32));
stub_fn!(glClearNamedBufferData, (), (buffer: u32, internalformat: u32, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearNamedBufferDataEXT, (), (buffer: u32, internalformat: u32, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearNamedBufferSubData, (), (buffer: u32, internalformat: u32, offset: isize, size: isize, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearNamedBufferSubDataEXT, (), (buffer: u32, internalformat: u32, offset: isize, size: isize, format: u32, type_: u32, data: *const std::ffi::c_void));
stub_fn!(glClearNamedFramebufferfi, (), (framebuffer: u32, buffer: u32, drawbuffer: i32, depth: f32, stencil: i32));
stub_fn!(glClearNamedFramebufferfv, (), (framebuffer: u32, buffer: u32, drawbuffer: i32, value: *const f32));
stub_fn!(glClearNamedFramebufferiv, (), (framebuffer: u32, buffer: u32, drawbuffer: i32, value: *const i32));
stub_fn!(glClearNamedFramebufferuiv, (), (framebuffer: u32, buffer: u32, drawbuffer: i32, value: *const u32));
stub_fn!(glClientAttribDefaultEXT, (), (mask: u32));
stub_fn!(glClipControl, (), (origin: u32, depth: u32));
stub_fn!(glColorP3ui, (), (type_: u32, color: u32));
stub_fn!(glColorP3uiv, (), (type_: u32, color: *const u32));
stub_fn!(glColorP4ui, (), (type_: u32, color: u32));
stub_fn!(glColorP4uiv, (), (type_: u32, color: *const u32));
stub_fn!(glCommandListSegmentsNV, (), (list: u32, segments: u32));
stub_fn!(glCompileCommandListNV, (), (list: u32));
stub_fn!(glCompileShaderIncludeARB, (), (shader: u32, count: i32, path: *const *const std::ffi::c_char, length: *const i32));
stub_fn!(glCompressedMultiTexImage1DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: u32, width: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedMultiTexImage2DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: u32, width: i32, height: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedMultiTexImage3DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: u32, width: i32, height: i32, depth: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedMultiTexSubImage1DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, width: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedMultiTexSubImage2DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedMultiTexSubImage3DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTexImage1D, (), (target: u32, level: i32, internalformat: u32, width: i32, border: i32, imageSize: i32, data: *const std::ffi::c_void));
stub_fn!(glCompressedTexSubImage1D, (), (target: u32, level: i32, xoffset: i32, width: i32, format: u32, imageSize: i32, data: *const std::ffi::c_void));
stub_fn!(glCompressedTextureImage1DEXT, (), (texture: u32, target: u32, level: i32, internalformat: u32, width: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTextureImage2DEXT, (), (texture: u32, target: u32, level: i32, internalformat: u32, width: i32, height: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTextureImage3DEXT, (), (texture: u32, target: u32, level: i32, internalformat: u32, width: i32, height: i32, depth: i32, border: i32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage1D, (), (texture: u32, level: i32, xoffset: i32, width: i32, format: u32, imageSize: i32, data: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage1DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, width: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage2D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, imageSize: i32, data: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage2DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage3D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, imageSize: i32, data: *const std::ffi::c_void));
stub_fn!(glCompressedTextureSubImage3DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, imageSize: i32, bits: *const std::ffi::c_void));
stub_fn!(glConservativeRasterParameterfNV, (), (pname: u32, value: f32));
stub_fn!(glConservativeRasterParameteriNV, (), (pname: u32, param: i32));
stub_fn!(glCopyImageSubData, (), (srcName: u32, srcTarget: u32, srcLevel: i32, srcX: i32, srcY: i32, srcZ: i32, dstName: u32, dstTarget: u32, dstLevel: i32, dstX: i32, dstY: i32, dstZ: i32, srcWidth: i32, srcHeight: i32, srcDepth: i32));
stub_fn!(glCopyMultiTexImage1DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: u32, x: i32, y: i32, width: i32, border: i32));
stub_fn!(glCopyMultiTexImage2DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: u32, x: i32, y: i32, width: i32, height: i32, border: i32));
stub_fn!(glCopyMultiTexSubImage1DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, x: i32, y: i32, width: i32));
stub_fn!(glCopyMultiTexSubImage2DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCopyMultiTexSubImage3DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCopyNamedBufferSubData, (), (readBuffer: u32, writeBuffer: u32, readOffset: isize, writeOffset: isize, size: isize));
stub_fn!(glCopyPathNV, (), (resultPath: u32, srcPath: u32));
stub_fn!(glCopyTexImage1D, (), (target: u32, level: i32, internalformat: u32, x: i32, y: i32, width: i32, border: i32));
stub_fn!(glCopyTexSubImage1D, (), (target: u32, level: i32, xoffset: i32, x: i32, y: i32, width: i32));
stub_fn!(glCopyTextureImage1DEXT, (), (texture: u32, target: u32, level: i32, internalformat: u32, x: i32, y: i32, width: i32, border: i32));
stub_fn!(glCopyTextureImage2DEXT, (), (texture: u32, target: u32, level: i32, internalformat: u32, x: i32, y: i32, width: i32, height: i32, border: i32));
stub_fn!(glCopyTextureSubImage1D, (), (texture: u32, level: i32, xoffset: i32, x: i32, y: i32, width: i32));
stub_fn!(glCopyTextureSubImage1DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, x: i32, y: i32, width: i32));
stub_fn!(glCopyTextureSubImage2D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCopyTextureSubImage2DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCopyTextureSubImage3D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCopyTextureSubImage3DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glCoverFillPathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, coverMode: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glCoverFillPathNV, (), (path: u32, coverMode: u32));
stub_fn!(glCoverStrokePathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, coverMode: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glCoverStrokePathNV, (), (path: u32, coverMode: u32));
stub_fn!(glCoverageModulationNV, (), (components: u32));
stub_fn!(glCoverageModulationTableNV, (), (n: i32, v: *const f32));
stub_fn!(glCreateBuffers, (), (n: i32, buffers: *mut u32));
stub_fn!(glCreateCommandListsNV, (), (n: i32, lists: *mut u32));
stub_fn!(glCreateFramebuffers, (), (n: i32, framebuffers: *mut u32));
stub_fn!(glCreatePerfQueryINTEL, (), (queryId: u32, queryHandle: *mut u32));
stub_fn!(glCreateProgramPipelines, (), (n: i32, pipelines: *mut u32));
stub_fn!(glCreateQueries, (), (target: u32, n: i32, ids: *mut u32));
stub_fn!(glCreateRenderbuffers, (), (n: i32, renderbuffers: *mut u32));
stub_fn!(glCreateSamplers, (), (n: i32, samplers: *mut u32));
stub_fn!(glCreateShaderProgramEXT, u32, (type_: u32, string: *const std::ffi::c_char));
stub_fn!(glCreateStatesNV, (), (n: i32, states: *mut u32));
stub_fn!(glCreateSyncFromCLeventARB, *mut std::ffi::c_void, (context: *mut std::ffi::c_void, event: *mut std::ffi::c_void, flags: u32));
stub_fn!(glCreateTextures, (), (target: u32, n: i32, textures: *mut u32));
stub_fn!(glCreateTransformFeedbacks, (), (n: i32, ids: *mut u32));
stub_fn!(glCreateVertexArrays, (), (n: i32, arrays: *mut u32));
stub_fn!(glDebugMessageCallbackARB, (), (callback: *mut std::ffi::c_void, userParam: *const std::ffi::c_void));
stub_fn!(glDebugMessageControl, (), (source: u32, type_: u32, severity: u32, count: i32, ids: *const u32, enabled: u8));
stub_fn!(glDebugMessageControlARB, (), (source: u32, type_: u32, severity: u32, count: i32, ids: *const u32, enabled: u8));
stub_fn!(glDebugMessageInsert, (), (source: u32, type_: u32, id: u32, severity: u32, length: i32, buf: *const std::ffi::c_char));
stub_fn!(glDebugMessageInsertARB, (), (source: u32, type_: u32, id: u32, severity: u32, length: i32, buf: *const std::ffi::c_char));
stub_fn!(glDeleteCommandListsNV, (), (n: i32, lists: *const u32));
stub_fn!(glDeleteNamedStringARB, (), (namelen: i32, name: *const std::ffi::c_char));
stub_fn!(glDeletePathsNV, (), (path: u32, range: i32));
stub_fn!(glDeletePerfMonitorsAMD, (), (n: i32, monitors: *mut u32));
stub_fn!(glDeletePerfQueryINTEL, (), (queryHandle: u32));
stub_fn!(glDeleteProgramPipelines, (), (n: i32, pipelines: *const u32));
stub_fn!(glDeleteStatesNV, (), (n: i32, states: *const u32));
stub_fn!(glDepthBoundsdNV, (), (zmin: f64, zmax: f64));
stub_fn!(glDepthRangeArraydvNV, (), (first: u32, count: i32, v: *const f64));
stub_fn!(glDepthRangeArrayv, (), (first: u32, count: i32, v: *const f64));
stub_fn!(glDepthRangeIndexed, (), (index: u32, n: f64, f: f64));
stub_fn!(glDepthRangeIndexeddNV, (), (index: u32, n: f64, f: f64));
stub_fn!(glDepthRangedNV, (), (zNear: f64, zFar: f64));
stub_fn!(glDisableIndexedEXT, (), (target: u32, index: u32));
stub_fn!(glDisableVertexArrayAttrib, (), (vaobj: u32, index: u32));
stub_fn!(glDisableVertexArrayAttribEXT, (), (vaobj: u32, index: u32));
stub_fn!(glDisableVertexArrayEXT, (), (vaobj: u32, array: u32));
stub_fn!(glDispatchComputeGroupSizeARB, (), (num_groups_x: u32, num_groups_y: u32, num_groups_z: u32, group_size_x: u32, group_size_y: u32, group_size_z: u32));
stub_fn!(glDispatchComputeIndirect, (), (indirect: isize));
stub_fn!(glDrawArraysInstancedARB, (), (mode: u32, first: i32, count: i32, primcount: i32));
stub_fn!(glDrawArraysInstancedEXT, (), (mode: u32, start: i32, count: i32, primcount: i32));
stub_fn!(glDrawCommandsAddressNV, (), (primitiveMode: u32, indirects: *const u64, sizes: *const i32, count: u32));
stub_fn!(glDrawCommandsNV, (), (primitiveMode: u32, buffer: u32, indirects: *const isize, sizes: *const i32, count: u32));
stub_fn!(glDrawCommandsStatesAddressNV, (), (indirects: *const u64, sizes: *const i32, states: *const u32, fbos: *const u32, count: u32));
stub_fn!(glDrawCommandsStatesNV, (), (buffer: u32, indirects: *const isize, sizes: *const i32, states: *const u32, fbos: *const u32, count: u32));
stub_fn!(glDrawElementsInstancedARB, (), (mode: u32, count: i32, type_: u32, indices: *const std::ffi::c_void, primcount: i32));
stub_fn!(glDrawElementsInstancedEXT, (), (mode: u32, count: i32, type_: u32, indices: *const std::ffi::c_void, primcount: i32));
stub_fn!(glDrawMeshTasksIndirectNV, (), (indirect: isize));
stub_fn!(glDrawMeshTasksNV, (), (first: u32, count: u32));
stub_fn!(glDrawVkImageNV, (), (vkImage: u64, sampler: u32, x0: f32, y0: f32, x1: f32, y1: f32, z: f32, s0: f32, t0: f32, s1: f32, t1: f32));
stub_fn!(glEGLImageTargetTexStorageEXT, (), (target: u32, image: *mut std::ffi::c_void, attrib_list: *const i32));
stub_fn!(glEGLImageTargetTextureStorageEXT, (), (texture: u32, image: *mut std::ffi::c_void, attrib_list: *const i32));
stub_fn!(glEnableIndexedEXT, (), (target: u32, index: u32));
stub_fn!(glEnableVertexArrayAttrib, (), (vaobj: u32, index: u32));
stub_fn!(glEnableVertexArrayAttribEXT, (), (vaobj: u32, index: u32));
stub_fn!(glEnableVertexArrayEXT, (), (vaobj: u32, array: u32));
stub_fn!(glEvaluateDepthValuesARB, (), ());
stub_fn!(glFlushMappedNamedBufferRange, (), (buffer: u32, offset: isize, length: isize));
stub_fn!(glFlushMappedNamedBufferRangeEXT, (), (buffer: u32, offset: isize, length: isize));
stub_fn!(glFragmentCoverageColorNV, (), (color: u32));
stub_fn!(glFramebufferDrawBufferEXT, (), (framebuffer: u32, mode: u32));
stub_fn!(glFramebufferDrawBuffersEXT, (), (framebuffer: u32, n: i32, bufs: *const u32));
stub_fn!(glFramebufferFetchBarrierEXT, (), ());
stub_fn!(glFramebufferParameteri, (), (target: u32, pname: u32, param: i32));
stub_fn!(glFramebufferParameteriMESA, (), (target: u32, pname: u32, param: i32));
stub_fn!(glFramebufferReadBufferEXT, (), (framebuffer: u32, mode: u32));
stub_fn!(glFramebufferSampleLocationsfvARB, (), (target: u32, start: u32, count: i32, v: *const f32));
stub_fn!(glFramebufferSampleLocationsfvNV, (), (target: u32, start: u32, count: i32, v: *const f32));
// glFramebufferTexture / glFramebufferTextureLayerARB 已真实化（framebuffer.rs），生成器基于 nm 自动跳过
stub_fn!(glFramebufferTextureARB, (), (target: u32, attachment: u32, texture: u32, level: i32));
stub_fn!(glFramebufferTextureFaceARB, (), (target: u32, attachment: u32, texture: u32, level: i32, face: u32));
stub_fn!(glFramebufferTextureMultiviewOVR, (), (target: u32, attachment: u32, texture: u32, level: i32, baseViewIndex: i32, numViews: i32));
stub_fn!(glGenPathsNV, u32, (range: i32));
stub_fn!(glGenPerfMonitorsAMD, (), (n: i32, monitors: *mut u32));
stub_fn!(glGenProgramPipelines, (), (n: i32, pipelines: *mut u32));
stub_fn!(glGenerateMultiTexMipmapEXT, (), (texunit: u32, target: u32));
stub_fn!(glGenerateTextureMipmap, (), (texture: u32));
stub_fn!(glGenerateTextureMipmapEXT, (), (texture: u32, target: u32));
stub_fn!(glGetActiveAtomicCounterBufferiv, (), (program: u32, bufferIndex: u32, pname: u32, params: *mut i32));
stub_fn!(glGetActiveSubroutineName, (), (program: u32, shadertype: u32, index: u32, bufSize: i32, length: *mut i32, name: *mut std::ffi::c_char));
stub_fn!(glGetActiveSubroutineUniformName, (), (program: u32, shadertype: u32, index: u32, bufSize: i32, length: *mut i32, name: *mut std::ffi::c_char));
stub_fn!(glGetActiveSubroutineUniformiv, (), (program: u32, shadertype: u32, index: u32, pname: u32, values: *mut i32));
stub_fn!(glGetBooleanIndexedvEXT, (), (target: u32, index: u32, data: *mut u8));
stub_fn!(glGetBufferParameterui64vNV, (), (target: u32, pname: u32, params: *mut u64));
stub_fn!(glGetCommandHeaderNV, u32, (tokenID: u32, size: u32));
stub_fn!(glGetCompressedMultiTexImageEXT, (), (texunit: u32, target: u32, lod: i32, img: *mut std::ffi::c_void));
stub_fn!(glGetCompressedTexImage, (), (target: u32, level: i32, img: *mut std::ffi::c_void));
stub_fn!(glGetCompressedTextureImage, (), (texture: u32, level: i32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetCompressedTextureImageEXT, (), (texture: u32, target: u32, lod: i32, img: *mut std::ffi::c_void));
stub_fn!(glGetCompressedTextureSubImage, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetCoverageModulationTableNV, (), (bufSize: i32, v: *mut f32));
stub_fn!(glGetDebugMessageLog, u32, (count: u32, bufSize: i32, sources: *mut u32, types: *mut u32, ids: *mut u32, severities: *mut u32, lengths: *mut i32, messageLog: *mut std::ffi::c_char));
stub_fn!(glGetDebugMessageLogARB, u32, (count: u32, bufSize: i32, sources: *mut u32, types: *mut u32, ids: *mut u32, severities: *mut u32, lengths: *mut i32, messageLog: *mut std::ffi::c_char));
stub_fn!(glGetDoubleIndexedvEXT, (), (target: u32, index: u32, data: *mut f64));
stub_fn!(glGetFirstPerfQueryIdINTEL, (), (queryId: *mut u32));
stub_fn!(glGetFloatIndexedvEXT, (), (target: u32, index: u32, data: *mut f32));
stub_fn!(glGetFramebufferParameterivEXT, (), (framebuffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetFramebufferParameterivMESA, (), (target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetGraphicsResetStatus, u32, ());
stub_fn!(glGetGraphicsResetStatusARB, u32, ());
stub_fn!(glGetImageHandleARB, u64, (texture: u32, level: i32, layered: u8, layer: i32, format: u32));
stub_fn!(glGetImageHandleNV, u64, (texture: u32, level: i32, layered: u8, layer: i32, format: u32));
stub_fn!(glGetIntegerIndexedvEXT, (), (target: u32, index: u32, data: *mut i32));
stub_fn!(glGetIntegerui64vNV, (), (value: u32, result: *mut u64));
stub_fn!(glGetInternalformatSampleivNV, (), (target: u32, internalformat: u32, samples: i32, pname: u32, count: i32, params: *mut i32));
stub_fn!(glGetLightfv, (), (light: u32, pname: u32, params: *mut f32));
stub_fn!(glGetLightiv, (), (light: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMapAttribParameterfvNV, (), (target: u32, index: u32, pname: u32, params: *mut f32));
stub_fn!(glGetMapAttribParameterivNV, (), (target: u32, index: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMaterialfv, (), (face: u32, pname: u32, params: *mut f32));
stub_fn!(glGetMaterialiv, (), (face: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMemoryObjectDetachedResourcesuivNV, (), (memory: u32, pname: u32, first: i32, count: i32, params: *mut u32));
stub_fn!(glGetMultiTexEnvfvEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut f32));
stub_fn!(glGetMultiTexEnvivEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMultiTexGendvEXT, (), (texunit: u32, coord: u32, pname: u32, params: *mut f64));
stub_fn!(glGetMultiTexGenfvEXT, (), (texunit: u32, coord: u32, pname: u32, params: *mut f32));
stub_fn!(glGetMultiTexGenivEXT, (), (texunit: u32, coord: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMultiTexImageEXT, (), (texunit: u32, target: u32, level: i32, format: u32, type_: u32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetMultiTexLevelParameterfvEXT, (), (texunit: u32, target: u32, level: i32, pname: u32, params: *mut f32));
stub_fn!(glGetMultiTexLevelParameterivEXT, (), (texunit: u32, target: u32, level: i32, pname: u32, params: *mut i32));
stub_fn!(glGetMultiTexParameterIivEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetMultiTexParameterIuivEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut u32));
stub_fn!(glGetMultiTexParameterfvEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut f32));
stub_fn!(glGetMultiTexParameterivEXT, (), (texunit: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedBufferParameteri64v, (), (buffer: u32, pname: u32, params: *mut i64));
stub_fn!(glGetNamedBufferParameteriv, (), (buffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedBufferParameterivEXT, (), (buffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedBufferParameterui64vNV, (), (buffer: u32, pname: u32, params: *mut u64));
stub_fn!(glGetNamedBufferPointerv, (), (buffer: u32, pname: u32, params: *mut *mut std::ffi::c_void));
stub_fn!(glGetNamedBufferPointervEXT, (), (buffer: u32, pname: u32, params: *mut *mut std::ffi::c_void));
stub_fn!(glGetNamedBufferSubData, (), (buffer: u32, offset: isize, size: isize, data: *mut std::ffi::c_void));
stub_fn!(glGetNamedBufferSubDataEXT, (), (buffer: u32, offset: isize, size: isize, data: *mut std::ffi::c_void));
stub_fn!(glGetNamedFramebufferAttachmentParameteriv, (), (framebuffer: u32, attachment: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedFramebufferAttachmentParameterivEXT, (), (framebuffer: u32, attachment: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedFramebufferParameteriv, (), (framebuffer: u32, pname: u32, param: *mut i32));
stub_fn!(glGetNamedFramebufferParameterivEXT, (), (framebuffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedProgramLocalParameterIivEXT, (), (program: u32, target: u32, index: u32, params: *mut i32));
stub_fn!(glGetNamedProgramLocalParameterIuivEXT, (), (program: u32, target: u32, index: u32, params: *mut u32));
stub_fn!(glGetNamedProgramLocalParameterdvEXT, (), (program: u32, target: u32, index: u32, params: *mut f64));
stub_fn!(glGetNamedProgramLocalParameterfvEXT, (), (program: u32, target: u32, index: u32, params: *mut f32));
stub_fn!(glGetNamedProgramStringEXT, (), (program: u32, target: u32, pname: u32, string: *mut std::ffi::c_void));
stub_fn!(glGetNamedProgramivEXT, (), (program: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedRenderbufferParameteriv, (), (renderbuffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedRenderbufferParameterivEXT, (), (renderbuffer: u32, pname: u32, params: *mut i32));
stub_fn!(glGetNamedStringARB, (), (namelen: i32, name: *const std::ffi::c_char, bufSize: i32, stringlen: *mut i32, string: *mut std::ffi::c_char));
stub_fn!(glGetNamedStringivARB, (), (namelen: i32, name: *const std::ffi::c_char, pname: u32, params: *mut i32));
stub_fn!(glGetNextPerfQueryIdINTEL, (), (queryId: u32, nextQueryId: *mut u32));
stub_fn!(glGetObjectLabel, (), (identifier: u32, name: u32, bufSize: i32, length: *mut i32, label: *mut std::ffi::c_char));
stub_fn!(glGetObjectLabelEXT, (), (type_: u32, object: u32, bufSize: i32, length: *mut i32, label: *mut std::ffi::c_char));
stub_fn!(glGetObjectPtrLabel, (), (ptr: *const std::ffi::c_void, bufSize: i32, length: *mut i32, label: *mut std::ffi::c_char));
stub_fn!(glGetPathCommandsNV, (), (path: u32, commands: *mut u8));
stub_fn!(glGetPathCoordsNV, (), (path: u32, coords: *mut f32));
stub_fn!(glGetPathDashArrayNV, (), (path: u32, dashArray: *mut f32));
stub_fn!(glGetPathLengthNV, f32, (path: u32, startSegment: i32, numSegments: i32));
stub_fn!(glGetPathMetricRangeNV, (), (metricQueryMask: u32, firstPathName: u32, numPaths: i32, stride: i32, metrics: *mut f32));
stub_fn!(glGetPathMetricsNV, (), (metricQueryMask: u32, numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, stride: i32, metrics: *mut f32));
stub_fn!(glGetPathParameterfvNV, (), (path: u32, pname: u32, value: *mut f32));
stub_fn!(glGetPathParameterivNV, (), (path: u32, pname: u32, value: *mut i32));
stub_fn!(glGetPathSpacingNV, (), (pathListMode: u32, numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, advanceScale: f32, kerningScale: f32, transformType: u32, returnedSpacing: *mut f32));
stub_fn!(glGetPerfCounterInfoINTEL, (), (queryId: u32, counterId: u32, counterNameLength: u32, counterName: *mut std::ffi::c_char, counterDescLength: u32, counterDesc: *mut std::ffi::c_char, counterOffset: *mut u32, counterDataSize: *mut u32, counterTypeEnum: *mut u32, counterDataTypeEnum: *mut u32, rawCounterMaxValue: *mut u64));
stub_fn!(glGetPerfMonitorCounterDataAMD, (), (monitor: u32, pname: u32, dataSize: i32, data: *mut u32, bytesWritten: *mut i32));
stub_fn!(glGetPerfMonitorCounterInfoAMD, (), (group: u32, counter: u32, pname: u32, data: *mut std::ffi::c_void));
stub_fn!(glGetPerfMonitorCounterStringAMD, (), (group: u32, counter: u32, bufSize: i32, length: *mut i32, counterString: *mut std::ffi::c_char));
stub_fn!(glGetPerfMonitorCountersAMD, (), (group: u32, numCounters: *mut i32, maxActiveCounters: *mut i32, counterSize: i32, counters: *mut u32));
stub_fn!(glGetPerfMonitorGroupStringAMD, (), (group: u32, bufSize: i32, length: *mut i32, groupString: *mut std::ffi::c_char));
stub_fn!(glGetPerfMonitorGroupsAMD, (), (numGroups: *mut i32, groupsSize: i32, groups: *mut u32));
stub_fn!(glGetPerfQueryDataINTEL, (), (queryHandle: u32, flags: u32, dataSize: i32, data: *mut std::ffi::c_void, bytesWritten: *mut u32));
stub_fn!(glGetPerfQueryIdByNameINTEL, (), (queryName: *mut std::ffi::c_char, queryId: *mut u32));
stub_fn!(glGetPerfQueryInfoINTEL, (), (queryId: u32, queryNameLength: u32, queryName: *mut std::ffi::c_char, dataSize: *mut u32, noCounters: *mut u32, noInstances: *mut u32, capsMask: *mut u32));
stub_fn!(glGetProgramBinary, (), (program: u32, bufSize: i32, length: *mut i32, binaryFormat: *mut u32, binary: *mut std::ffi::c_void));
stub_fn!(glGetProgramInterfaceiv, (), (program: u32, programInterface: u32, pname: u32, params: *mut i32));
stub_fn!(glGetProgramPipelineInfoLog, (), (pipeline: u32, bufSize: i32, length: *mut i32, infoLog: *mut std::ffi::c_char));
stub_fn!(glGetProgramPipelineiv, (), (pipeline: u32, pname: u32, params: *mut i32));
stub_fn!(glGetProgramResourceIndex, u32, (program: u32, programInterface: u32, name: *const std::ffi::c_char));
stub_fn!(glGetProgramResourceLocation, i32, (program: u32, programInterface: u32, name: *const std::ffi::c_char));
stub_fn!(glGetProgramResourceLocationIndex, i32, (program: u32, programInterface: u32, name: *const std::ffi::c_char));
stub_fn!(glGetProgramResourceName, (), (program: u32, programInterface: u32, index: u32, bufSize: i32, length: *mut i32, name: *mut std::ffi::c_char));
stub_fn!(glGetProgramResourcefvNV, (), (program: u32, programInterface: u32, index: u32, propCount: i32, props: *const u32, count: i32, length: *mut i32, params: *mut f32));
stub_fn!(glGetProgramResourceiv, (), (program: u32, programInterface: u32, index: u32, propCount: i32, props: *const u32, count: i32, length: *mut i32, params: *mut i32));
stub_fn!(glGetProgramStageiv, (), (program: u32, shadertype: u32, pname: u32, values: *mut i32));
stub_fn!(glGetQueryBufferObjecti64v, (), (id: u32, buffer: u32, pname: u32, offset: isize));
stub_fn!(glGetQueryBufferObjectiv, (), (id: u32, buffer: u32, pname: u32, offset: isize));
stub_fn!(glGetQueryBufferObjectui64v, (), (id: u32, buffer: u32, pname: u32, offset: isize));
stub_fn!(glGetQueryBufferObjectuiv, (), (id: u32, buffer: u32, pname: u32, offset: isize));
stub_fn!(glGetQueryObjecti64vEXT, (), (id: u32, pname: u32, params: *mut i64));
stub_fn!(glGetQueryObjectivEXT, (), (id: u32, pname: u32, params: *mut i32));
stub_fn!(glGetShaderPrecisionFormat, (), (shadertype: u32, precisiontype: u32, range: *mut i32, precision: *mut i32));
stub_fn!(glGetShadingRateImagePaletteNV, (), (viewport: u32, entry: u32, rate: *mut u32));
stub_fn!(glGetShadingRateSampleLocationivNV, (), (rate: u32, samples: u32, index: u32, location: *mut i32));
stub_fn!(glGetStageIndexNV, u16, (shadertype: u32));
stub_fn!(glGetSubroutineIndex, u32, (program: u32, shadertype: u32, name: *const std::ffi::c_char));
stub_fn!(glGetSubroutineUniformLocation, i32, (program: u32, shadertype: u32, name: *const std::ffi::c_char));
stub_fn!(glGetSynciv, (), (sync: *mut std::ffi::c_void, pname: u32, count: i32, length: *mut i32, values: *mut i32));
stub_fn!(glGetTexEnvfv, (), (target: u32, pname: u32, params: *mut f32));
stub_fn!(glGetTexEnviv, (), (target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureHandleARB, u64, (texture: u32));
stub_fn!(glGetTextureHandleNV, u64, (texture: u32));
stub_fn!(glGetTextureImage, (), (texture: u32, level: i32, format: u32, type_: u32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetTextureImageEXT, (), (texture: u32, target: u32, level: i32, format: u32, type_: u32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetTextureLevelParameterfv, (), (texture: u32, level: i32, pname: u32, params: *mut f32));
stub_fn!(glGetTextureLevelParameterfvEXT, (), (texture: u32, target: u32, level: i32, pname: u32, params: *mut f32));
stub_fn!(glGetTextureLevelParameteriv, (), (texture: u32, level: i32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureLevelParameterivEXT, (), (texture: u32, target: u32, level: i32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureParameterIiv, (), (texture: u32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureParameterIivEXT, (), (texture: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureParameterIuiv, (), (texture: u32, pname: u32, params: *mut u32));
stub_fn!(glGetTextureParameterIuivEXT, (), (texture: u32, target: u32, pname: u32, params: *mut u32));
stub_fn!(glGetTextureParameterfv, (), (texture: u32, pname: u32, params: *mut f32));
stub_fn!(glGetTextureParameterfvEXT, (), (texture: u32, target: u32, pname: u32, params: *mut f32));
stub_fn!(glGetTextureParameteriv, (), (texture: u32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureParameterivEXT, (), (texture: u32, target: u32, pname: u32, params: *mut i32));
stub_fn!(glGetTextureSamplerHandleARB, u64, (texture: u32, sampler: u32));
stub_fn!(glGetTextureSamplerHandleNV, u64, (texture: u32, sampler: u32));
stub_fn!(glGetTextureSubImage, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, type_: u32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetUniformSubroutineuiv, (), (shadertype: u32, location: i32, params: *mut u32));
stub_fn!(glGetUniformdv, (), (program: u32, location: i32, params: *mut f64));
stub_fn!(glGetUniformi64vARB, (), (program: u32, location: i32, params: *mut i64));
stub_fn!(glGetUniformi64vNV, (), (program: u32, location: i32, params: *mut i64));
stub_fn!(glGetUniformui64vARB, (), (program: u32, location: i32, params: *mut u64));
stub_fn!(glGetUniformui64vNV, (), (program: u32, location: i32, params: *mut u64));
stub_fn!(glGetVertexArrayIndexed64iv, (), (vaobj: u32, index: u32, pname: u32, param: *mut i64));
stub_fn!(glGetVertexArrayIndexediv, (), (vaobj: u32, index: u32, pname: u32, param: *mut i32));
stub_fn!(glGetVertexArrayIntegervEXT, (), (vaobj: u32, pname: u32, param: *mut i32));
stub_fn!(glGetVertexArrayPointervEXT, (), (vaobj: u32, pname: u32, param: *mut *mut std::ffi::c_void));
stub_fn!(glGetVertexArrayiv, (), (vaobj: u32, pname: u32, param: *mut i32));
stub_fn!(glGetVertexAttribLdv, (), (index: u32, pname: u32, params: *mut f64));
stub_fn!(glGetVertexAttribLi64vNV, (), (index: u32, pname: u32, params: *mut i64));
stub_fn!(glGetVertexAttribLui64vARB, (), (index: u32, pname: u32, params: *mut u64));
stub_fn!(glGetVertexAttribLui64vNV, (), (index: u32, pname: u32, params: *mut u64));
stub_fn!(glGetVertexAttribfv, (), (index: u32, pname: u32, params: *mut f32));
stub_fn!(glGetVkProcAddrNV, *mut std::ffi::c_void, (name: *const std::ffi::c_char));
stub_fn!(glGetnCompressedTexImage, (), (target: u32, lod: i32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetnCompressedTexImageARB, (), (target: u32, lod: i32, bufSize: i32, img: *mut std::ffi::c_void));
stub_fn!(glGetnTexImage, (), (target: u32, level: i32, format: u32, type_: u32, bufSize: i32, pixels: *mut std::ffi::c_void));
stub_fn!(glGetnTexImageARB, (), (target: u32, level: i32, format: u32, type_: u32, bufSize: i32, img: *mut std::ffi::c_void));
stub_fn!(glGetnUniformdv, (), (program: u32, location: i32, bufSize: i32, params: *mut f64));
stub_fn!(glGetnUniformdvARB, (), (program: u32, location: i32, bufSize: i32, params: *mut f64));
stub_fn!(glGetnUniformfv, (), (program: u32, location: i32, bufSize: i32, params: *mut f32));
stub_fn!(glGetnUniformfvARB, (), (program: u32, location: i32, bufSize: i32, params: *mut f32));
stub_fn!(glGetnUniformi64vARB, (), (program: u32, location: i32, bufSize: i32, params: *mut i64));
stub_fn!(glGetnUniformiv, (), (program: u32, location: i32, bufSize: i32, params: *mut i32));
stub_fn!(glGetnUniformivARB, (), (program: u32, location: i32, bufSize: i32, params: *mut i32));
stub_fn!(glGetnUniformui64vARB, (), (program: u32, location: i32, bufSize: i32, params: *mut u64));
stub_fn!(glGetnUniformuiv, (), (program: u32, location: i32, bufSize: i32, params: *mut u32));
stub_fn!(glGetnUniformuivARB, (), (program: u32, location: i32, bufSize: i32, params: *mut u32));
stub_fn!(glInsertEventMarkerEXT, (), (length: i32, marker: *const std::ffi::c_char));
stub_fn!(glInterpolatePathsNV, (), (resultPath: u32, pathA: u32, pathB: u32, weight: f32));
stub_fn!(glInvalidateBufferData, (), (buffer: u32));
stub_fn!(glInvalidateBufferSubData, (), (buffer: u32, offset: isize, length: isize));
stub_fn!(glInvalidateFramebuffer, (), (target: u32, numAttachments: i32, attachments: *const u32));
stub_fn!(glInvalidateNamedFramebufferData, (), (framebuffer: u32, numAttachments: i32, attachments: *const u32));
stub_fn!(glInvalidateNamedFramebufferSubData, (), (framebuffer: u32, numAttachments: i32, attachments: *const u32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glInvalidateSubFramebuffer, (), (target: u32, numAttachments: i32, attachments: *const u32, x: i32, y: i32, width: i32, height: i32));
stub_fn!(glInvalidateTexImage, (), (texture: u32, level: i32));
stub_fn!(glInvalidateTexSubImage, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32));
stub_fn!(glIsBufferResidentNV, u8, (target: u32));
stub_fn!(glIsCommandListNV, u8, (list: u32));
stub_fn!(glIsEnabledIndexedEXT, u8, (target: u32, index: u32));
stub_fn!(glIsImageHandleResidentARB, u8, (handle: u64));
stub_fn!(glIsImageHandleResidentNV, u8, (handle: u64));
stub_fn!(glIsNamedBufferResidentNV, u8, (buffer: u32));
stub_fn!(glIsNamedStringARB, u8, (namelen: i32, name: *const std::ffi::c_char));
stub_fn!(glIsPathNV, u8, (path: u32));
stub_fn!(glIsPointInFillPathNV, u8, (path: u32, mask: u32, x: f32, y: f32));
stub_fn!(glIsPointInStrokePathNV, u8, (path: u32, x: f32, y: f32));
stub_fn!(glIsProgramPipeline, u8, (pipeline: u32));
stub_fn!(glIsStateNV, u8, (state: u32));
stub_fn!(glIsTextureHandleResidentARB, u8, (handle: u64));
stub_fn!(glIsTextureHandleResidentNV, u8, (handle: u64));
stub_fn!(glLabelObjectEXT, (), (type_: u32, object: u32, length: i32, label: *const std::ffi::c_char));
stub_fn!(glListDrawCommandsStatesClientNV, (), (list: u32, segment: u32, indirects: *const *const std::ffi::c_void, sizes: *const i32, states: *const u32, fbos: *const u32, count: u32));
stub_fn!(glLogicOp, (), (opcode: u32));
stub_fn!(glMakeBufferNonResidentNV, (), (target: u32));
stub_fn!(glMakeBufferResidentNV, (), (target: u32, access: u32));
stub_fn!(glMakeImageHandleNonResidentARB, (), (handle: u64));
stub_fn!(glMakeImageHandleNonResidentNV, (), (handle: u64));
stub_fn!(glMakeImageHandleResidentARB, (), (handle: u64, access: u32));
stub_fn!(glMakeImageHandleResidentNV, (), (handle: u64, access: u32));
stub_fn!(glMakeNamedBufferNonResidentNV, (), (buffer: u32));
stub_fn!(glMakeNamedBufferResidentNV, (), (buffer: u32, access: u32));
stub_fn!(glMakeTextureHandleNonResidentARB, (), (handle: u64));
stub_fn!(glMakeTextureHandleNonResidentNV, (), (handle: u64));
stub_fn!(glMakeTextureHandleResidentARB, (), (handle: u64));
stub_fn!(glMakeTextureHandleResidentNV, (), (handle: u64));
stub_fn!(glMapGrid1d, (), (un: i32, u1: f64, u2: f64));
stub_fn!(glMapGrid1f, (), (un: i32, u1: f32, u2: f32));
stub_fn!(glMapGrid2d, (), (un: i32, u1: f64, u2: f64, vn: i32, v1: f64, v2: f64));
stub_fn!(glMapGrid2f, (), (un: i32, u1: f32, u2: f32, vn: i32, v1: f32, v2: f32));
stub_fn!(glMaxShaderCompilerThreadsARB, (), (count: u32));
stub_fn!(glMaxShaderCompilerThreadsKHR, (), (count: u32));
stub_fn!(glMemoryBarrierByRegion, (), (barriers: u32));
stub_fn!(glMinSampleShading, (), (value: f32));
stub_fn!(glMinSampleShadingARB, (), (value: f32));
stub_fn!(glMultiDrawArraysIndirectBindlessCountNV, (), (mode: u32, indirect: *const std::ffi::c_void, drawCount: i32, maxDrawCount: i32, stride: i32, vertexBufferCount: i32));
stub_fn!(glMultiDrawArraysIndirectBindlessNV, (), (mode: u32, indirect: *const std::ffi::c_void, drawCount: i32, stride: i32, vertexBufferCount: i32));
stub_fn!(glMultiDrawArraysIndirectCountARB, (), (mode: u32, indirect: *const std::ffi::c_void, drawcount: isize, maxdrawcount: i32, stride: i32));
stub_fn!(glMultiDrawElementsIndirectBindlessCountNV, (), (mode: u32, type_: u32, indirect: *const std::ffi::c_void, drawCount: i32, maxDrawCount: i32, stride: i32, vertexBufferCount: i32));
stub_fn!(glMultiDrawElementsIndirectBindlessNV, (), (mode: u32, type_: u32, indirect: *const std::ffi::c_void, drawCount: i32, stride: i32, vertexBufferCount: i32));
stub_fn!(glMultiDrawElementsIndirectCountARB, (), (mode: u32, type_: u32, indirect: *const std::ffi::c_void, drawcount: isize, maxdrawcount: i32, stride: i32));
stub_fn!(glMultiDrawMeshTasksIndirectCountNV, (), (indirect: isize, drawcount: isize, maxdrawcount: i32, stride: i32));
stub_fn!(glMultiDrawMeshTasksIndirectNV, (), (indirect: isize, drawcount: i32, stride: i32));
stub_fn!(glMultiTexBufferEXT, (), (texunit: u32, target: u32, internalformat: u32, buffer: u32));
stub_fn!(glMultiTexCoordP1ui, (), (texture: u32, type_: u32, coords: u32));
stub_fn!(glMultiTexCoordP1uiv, (), (texture: u32, type_: u32, coords: *const u32));
stub_fn!(glMultiTexCoordP2ui, (), (texture: u32, type_: u32, coords: u32));
stub_fn!(glMultiTexCoordP2uiv, (), (texture: u32, type_: u32, coords: *const u32));
stub_fn!(glMultiTexCoordP3ui, (), (texture: u32, type_: u32, coords: u32));
stub_fn!(glMultiTexCoordP3uiv, (), (texture: u32, type_: u32, coords: *const u32));
stub_fn!(glMultiTexCoordP4ui, (), (texture: u32, type_: u32, coords: u32));
stub_fn!(glMultiTexCoordP4uiv, (), (texture: u32, type_: u32, coords: *const u32));
stub_fn!(glMultiTexEnvfEXT, (), (texunit: u32, target: u32, pname: u32, param: f32));
stub_fn!(glMultiTexEnvfvEXT, (), (texunit: u32, target: u32, pname: u32, params: *const f32));
stub_fn!(glMultiTexEnviEXT, (), (texunit: u32, target: u32, pname: u32, param: i32));
stub_fn!(glMultiTexEnvivEXT, (), (texunit: u32, target: u32, pname: u32, params: *const i32));
stub_fn!(glMultiTexGendEXT, (), (texunit: u32, coord: u32, pname: u32, param: f64));
stub_fn!(glMultiTexGendvEXT, (), (texunit: u32, coord: u32, pname: u32, params: *const f64));
stub_fn!(glMultiTexGenfEXT, (), (texunit: u32, coord: u32, pname: u32, param: f32));
stub_fn!(glMultiTexGenfvEXT, (), (texunit: u32, coord: u32, pname: u32, params: *const f32));
stub_fn!(glMultiTexGeniEXT, (), (texunit: u32, coord: u32, pname: u32, param: i32));
stub_fn!(glMultiTexGenivEXT, (), (texunit: u32, coord: u32, pname: u32, params: *const i32));
stub_fn!(glMultiTexImage1DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: i32, width: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glMultiTexImage2DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: i32, width: i32, height: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glMultiTexImage3DEXT, (), (texunit: u32, target: u32, level: i32, internalformat: i32, width: i32, height: i32, depth: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glMultiTexParameterIivEXT, (), (texunit: u32, target: u32, pname: u32, params: *const i32));
stub_fn!(glMultiTexParameterIuivEXT, (), (texunit: u32, target: u32, pname: u32, params: *const u32));
stub_fn!(glMultiTexParameterfEXT, (), (texunit: u32, target: u32, pname: u32, param: f32));
stub_fn!(glMultiTexParameterfvEXT, (), (texunit: u32, target: u32, pname: u32, params: *const f32));
stub_fn!(glMultiTexParameteriEXT, (), (texunit: u32, target: u32, pname: u32, param: i32));
stub_fn!(glMultiTexParameterivEXT, (), (texunit: u32, target: u32, pname: u32, params: *const i32));
stub_fn!(glMultiTexRenderbufferEXT, (), (texunit: u32, target: u32, renderbuffer: u32));
stub_fn!(glMultiTexSubImage1DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, width: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glMultiTexSubImage2DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glMultiTexSubImage3DEXT, (), (texunit: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glNamedBufferAttachMemoryNV, (), (buffer: u32, memory: u32, offset: u64));
stub_fn!(glNamedBufferData, (), (buffer: u32, size: isize, data: *const std::ffi::c_void, usage: u32));
stub_fn!(glNamedBufferDataEXT, (), (buffer: u32, size: isize, data: *const std::ffi::c_void, usage: u32));
stub_fn!(glNamedBufferPageCommitmentARB, (), (buffer: u32, offset: isize, size: isize, commit: u8));
stub_fn!(glNamedBufferPageCommitmentEXT, (), (buffer: u32, offset: isize, size: isize, commit: u8));
stub_fn!(glNamedBufferPageCommitmentMemNV, (), (buffer: u32, offset: isize, size: isize, memory: u32, memOffset: u64, commit: u8));
stub_fn!(glNamedBufferStorage, (), (buffer: u32, size: isize, data: *const std::ffi::c_void, flags: u32));
stub_fn!(glNamedBufferStorageEXT, (), (buffer: u32, size: isize, data: *const std::ffi::c_void, flags: u32));
stub_fn!(glNamedBufferSubData, (), (buffer: u32, offset: isize, size: isize, data: *const std::ffi::c_void));
stub_fn!(glNamedBufferSubDataEXT, (), (buffer: u32, offset: isize, size: isize, data: *const std::ffi::c_void));
stub_fn!(glNamedCopyBufferSubDataEXT, (), (readBuffer: u32, writeBuffer: u32, readOffset: isize, writeOffset: isize, size: isize));
stub_fn!(glNamedFramebufferDrawBuffer, (), (framebuffer: u32, buf: u32));
stub_fn!(glNamedFramebufferDrawBuffers, (), (framebuffer: u32, n: i32, bufs: *const u32));
stub_fn!(glNamedFramebufferParameteri, (), (framebuffer: u32, pname: u32, param: i32));
stub_fn!(glNamedFramebufferParameteriEXT, (), (framebuffer: u32, pname: u32, param: i32));
stub_fn!(glNamedFramebufferReadBuffer, (), (framebuffer: u32, src: u32));
stub_fn!(glNamedFramebufferRenderbuffer, (), (framebuffer: u32, attachment: u32, renderbuffertarget: u32, renderbuffer: u32));
stub_fn!(glNamedFramebufferRenderbufferEXT, (), (framebuffer: u32, attachment: u32, renderbuffertarget: u32, renderbuffer: u32));
stub_fn!(glNamedFramebufferSampleLocationsfvARB, (), (framebuffer: u32, start: u32, count: i32, v: *const f32));
stub_fn!(glNamedFramebufferSampleLocationsfvNV, (), (framebuffer: u32, start: u32, count: i32, v: *const f32));
stub_fn!(glNamedFramebufferTexture, (), (framebuffer: u32, attachment: u32, texture: u32, level: i32));
stub_fn!(glNamedFramebufferTexture1DEXT, (), (framebuffer: u32, attachment: u32, textarget: u32, texture: u32, level: i32));
stub_fn!(glNamedFramebufferTexture2DEXT, (), (framebuffer: u32, attachment: u32, textarget: u32, texture: u32, level: i32));
stub_fn!(glNamedFramebufferTexture3DEXT, (), (framebuffer: u32, attachment: u32, textarget: u32, texture: u32, level: i32, zoffset: i32));
stub_fn!(glNamedFramebufferTextureEXT, (), (framebuffer: u32, attachment: u32, texture: u32, level: i32));
stub_fn!(glNamedFramebufferTextureFaceEXT, (), (framebuffer: u32, attachment: u32, texture: u32, level: i32, face: u32));
stub_fn!(glNamedFramebufferTextureLayer, (), (framebuffer: u32, attachment: u32, texture: u32, level: i32, layer: i32));
stub_fn!(glNamedFramebufferTextureLayerEXT, (), (framebuffer: u32, attachment: u32, texture: u32, level: i32, layer: i32));
stub_fn!(glNamedProgramLocalParameter4dEXT, (), (program: u32, target: u32, index: u32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glNamedProgramLocalParameter4dvEXT, (), (program: u32, target: u32, index: u32, params: *const f64));
stub_fn!(glNamedProgramLocalParameter4fEXT, (), (program: u32, target: u32, index: u32, x: f32, y: f32, z: f32, w: f32));
stub_fn!(glNamedProgramLocalParameter4fvEXT, (), (program: u32, target: u32, index: u32, params: *const f32));
stub_fn!(glNamedProgramLocalParameterI4iEXT, (), (program: u32, target: u32, index: u32, x: i32, y: i32, z: i32, w: i32));
stub_fn!(glNamedProgramLocalParameterI4ivEXT, (), (program: u32, target: u32, index: u32, params: *const i32));
stub_fn!(glNamedProgramLocalParameterI4uiEXT, (), (program: u32, target: u32, index: u32, x: u32, y: u32, z: u32, w: u32));
stub_fn!(glNamedProgramLocalParameterI4uivEXT, (), (program: u32, target: u32, index: u32, params: *const u32));
stub_fn!(glNamedProgramLocalParameters4fvEXT, (), (program: u32, target: u32, index: u32, count: i32, params: *const f32));
stub_fn!(glNamedProgramLocalParametersI4ivEXT, (), (program: u32, target: u32, index: u32, count: i32, params: *const i32));
stub_fn!(glNamedProgramLocalParametersI4uivEXT, (), (program: u32, target: u32, index: u32, count: i32, params: *const u32));
stub_fn!(glNamedProgramStringEXT, (), (program: u32, target: u32, format: u32, len: i32, string: *const std::ffi::c_void));
stub_fn!(glNamedRenderbufferStorage, (), (renderbuffer: u32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedRenderbufferStorageEXT, (), (renderbuffer: u32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedRenderbufferStorageMultisample, (), (renderbuffer: u32, samples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedRenderbufferStorageMultisampleAdvancedAMD, (), (renderbuffer: u32, samples: i32, storageSamples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedRenderbufferStorageMultisampleCoverageEXT, (), (renderbuffer: u32, coverageSamples: i32, colorSamples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedRenderbufferStorageMultisampleEXT, (), (renderbuffer: u32, samples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glNamedStringARB, (), (type_: u32, namelen: i32, name: *const std::ffi::c_char, stringlen: i32, string: *const std::ffi::c_char));
stub_fn!(glNormalP3ui, (), (type_: u32, coords: u32));
stub_fn!(glNormalP3uiv, (), (type_: u32, coords: *const u32));
stub_fn!(glObjectPtrLabel, (), (ptr: *const std::ffi::c_void, length: i32, label: *const std::ffi::c_char));
stub_fn!(glPatchParameterfv, (), (pname: u32, values: *const f32));
stub_fn!(glPatchParameteri, (), (pname: u32, value: i32));
stub_fn!(glPathCommandsNV, (), (path: u32, numCommands: i32, commands: *const u8, numCoords: i32, coordType: u32, coords: *const std::ffi::c_void));
stub_fn!(glPathCoordsNV, (), (path: u32, numCoords: i32, coordType: u32, coords: *const std::ffi::c_void));
stub_fn!(glPathCoverDepthFuncNV, (), (func: u32));
stub_fn!(glPathDashArrayNV, (), (path: u32, dashCount: i32, dashArray: *const f32));
stub_fn!(glPathGlyphIndexArrayNV, u32, (firstPathName: u32, fontTarget: u32, fontName: *const std::ffi::c_void, fontStyle: u32, firstGlyphIndex: u32, numGlyphs: i32, pathParameterTemplate: u32, emScale: f32));
stub_fn!(glPathGlyphIndexRangeNV, u32, (fontTarget: u32, fontName: *const std::ffi::c_void, fontStyle: u32, pathParameterTemplate: u32, emScale: f32, baseAndCount: *mut u32));
stub_fn!(glPathGlyphRangeNV, (), (firstPathName: u32, fontTarget: u32, fontName: *const std::ffi::c_void, fontStyle: u32, firstGlyph: u32, numGlyphs: i32, handleMissingGlyphs: u32, pathParameterTemplate: u32, emScale: f32));
stub_fn!(glPathGlyphsNV, (), (firstPathName: u32, fontTarget: u32, fontName: *const std::ffi::c_void, fontStyle: u32, numGlyphs: i32, type_: u32, charcodes: *const std::ffi::c_void, handleMissingGlyphs: u32, pathParameterTemplate: u32, emScale: f32));
stub_fn!(glPathMemoryGlyphIndexArrayNV, u32, (firstPathName: u32, fontTarget: u32, fontSize: isize, fontData: *const std::ffi::c_void, faceIndex: i32, firstGlyphIndex: u32, numGlyphs: i32, pathParameterTemplate: u32, emScale: f32));
stub_fn!(glPathParameterfNV, (), (path: u32, pname: u32, value: f32));
stub_fn!(glPathParameterfvNV, (), (path: u32, pname: u32, value: *const f32));
stub_fn!(glPathParameteriNV, (), (path: u32, pname: u32, value: i32));
stub_fn!(glPathParameterivNV, (), (path: u32, pname: u32, value: *const i32));
stub_fn!(glPathStencilDepthOffsetNV, (), (factor: f32, units: f32));
stub_fn!(glPathStencilFuncNV, (), (func: u32, ref_: i32, mask: u32));
stub_fn!(glPathStringNV, (), (path: u32, format: u32, length: i32, pathString: *const std::ffi::c_void));
stub_fn!(glPathSubCommandsNV, (), (path: u32, commandStart: i32, commandsToDelete: i32, numCommands: i32, commands: *const u8, numCoords: i32, coordType: u32, coords: *const std::ffi::c_void));
stub_fn!(glPathSubCoordsNV, (), (path: u32, coordStart: i32, numCoords: i32, coordType: u32, coords: *const std::ffi::c_void));
stub_fn!(glPixelZoom, (), (xfactor: f32, yfactor: f32));
stub_fn!(glPointAlongPathNV, u8, (path: u32, startSegment: i32, numSegments: i32, distance: f32, x: *mut f32, y: *mut f32, tangentX: *mut f32, tangentY: *mut f32));
stub_fn!(glPointSize, (), (size: f32));
stub_fn!(glPolygonOffsetClamp, (), (factor: f32, units: f32, clamp: f32));
stub_fn!(glPolygonOffsetClampEXT, (), (factor: f32, units: f32, clamp: f32));
stub_fn!(glPopDebugGroup, (), ());
stub_fn!(glPopGroupMarkerEXT, (), ());
stub_fn!(glPrimitiveBoundingBox, (), (minX: f32, minY: f32, minZ: f32, minW: f32, maxX: f32, maxY: f32, maxZ: f32, maxW: f32));
stub_fn!(glPrimitiveBoundingBoxARB, (), (minX: f32, minY: f32, minZ: f32, minW: f32, maxX: f32, maxY: f32, maxZ: f32, maxW: f32));
stub_fn!(glPrioritizeTextures, (), (n: i32, textures: *const u32, priorities: *const f32));
stub_fn!(glProgramBinary, (), (program: u32, binaryFormat: u32, binary: *const std::ffi::c_void, length: i32));
stub_fn!(glProgramParameteriARB, (), (program: u32, pname: u32, value: i32));
stub_fn!(glProgramPathFragmentInputGenNV, (), (program: u32, location: i32, genMode: u32, components: i32, coeffs: *const f32));
stub_fn!(glProgramUniform1d, (), (program: u32, location: i32, v0: f64));
stub_fn!(glProgramUniform1dEXT, (), (program: u32, location: i32, x: f64));
stub_fn!(glProgramUniform1dv, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform1dvEXT, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform1f, (), (program: u32, location: i32, v0: f32));
stub_fn!(glProgramUniform1fEXT, (), (program: u32, location: i32, v0: f32));
stub_fn!(glProgramUniform1fv, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform1fvEXT, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform1i, (), (program: u32, location: i32, v0: i32));
stub_fn!(glProgramUniform1i64ARB, (), (program: u32, location: i32, x: i64));
stub_fn!(glProgramUniform1i64NV, (), (program: u32, location: i32, x: i64));
stub_fn!(glProgramUniform1i64vARB, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform1i64vNV, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform1iEXT, (), (program: u32, location: i32, v0: i32));
stub_fn!(glProgramUniform1iv, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform1ivEXT, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform1ui, (), (program: u32, location: i32, v0: u32));
stub_fn!(glProgramUniform1ui64ARB, (), (program: u32, location: i32, x: u64));
stub_fn!(glProgramUniform1ui64NV, (), (program: u32, location: i32, x: u64));
stub_fn!(glProgramUniform1ui64vARB, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform1ui64vNV, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform1uiEXT, (), (program: u32, location: i32, v0: u32));
stub_fn!(glProgramUniform1uiv, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform1uivEXT, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform2d, (), (program: u32, location: i32, v0: f64, v1: f64));
stub_fn!(glProgramUniform2dEXT, (), (program: u32, location: i32, x: f64, y: f64));
stub_fn!(glProgramUniform2dv, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform2dvEXT, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform2f, (), (program: u32, location: i32, v0: f32, v1: f32));
stub_fn!(glProgramUniform2fEXT, (), (program: u32, location: i32, v0: f32, v1: f32));
stub_fn!(glProgramUniform2fv, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform2fvEXT, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform2i, (), (program: u32, location: i32, v0: i32, v1: i32));
stub_fn!(glProgramUniform2i64ARB, (), (program: u32, location: i32, x: i64, y: i64));
stub_fn!(glProgramUniform2i64NV, (), (program: u32, location: i32, x: i64, y: i64));
stub_fn!(glProgramUniform2i64vARB, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform2i64vNV, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform2iEXT, (), (program: u32, location: i32, v0: i32, v1: i32));
stub_fn!(glProgramUniform2iv, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform2ivEXT, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform2ui, (), (program: u32, location: i32, v0: u32, v1: u32));
stub_fn!(glProgramUniform2ui64ARB, (), (program: u32, location: i32, x: u64, y: u64));
stub_fn!(glProgramUniform2ui64NV, (), (program: u32, location: i32, x: u64, y: u64));
stub_fn!(glProgramUniform2ui64vARB, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform2ui64vNV, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform2uiEXT, (), (program: u32, location: i32, v0: u32, v1: u32));
stub_fn!(glProgramUniform2uiv, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform2uivEXT, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform3d, (), (program: u32, location: i32, v0: f64, v1: f64, v2: f64));
stub_fn!(glProgramUniform3dEXT, (), (program: u32, location: i32, x: f64, y: f64, z: f64));
stub_fn!(glProgramUniform3dv, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform3dvEXT, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform3f, (), (program: u32, location: i32, v0: f32, v1: f32, v2: f32));
stub_fn!(glProgramUniform3fEXT, (), (program: u32, location: i32, v0: f32, v1: f32, v2: f32));
stub_fn!(glProgramUniform3fv, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform3fvEXT, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform3i, (), (program: u32, location: i32, v0: i32, v1: i32, v2: i32));
stub_fn!(glProgramUniform3i64ARB, (), (program: u32, location: i32, x: i64, y: i64, z: i64));
stub_fn!(glProgramUniform3i64NV, (), (program: u32, location: i32, x: i64, y: i64, z: i64));
stub_fn!(glProgramUniform3i64vARB, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform3i64vNV, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform3iEXT, (), (program: u32, location: i32, v0: i32, v1: i32, v2: i32));
stub_fn!(glProgramUniform3iv, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform3ivEXT, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform3ui, (), (program: u32, location: i32, v0: u32, v1: u32, v2: u32));
stub_fn!(glProgramUniform3ui64ARB, (), (program: u32, location: i32, x: u64, y: u64, z: u64));
stub_fn!(glProgramUniform3ui64NV, (), (program: u32, location: i32, x: u64, y: u64, z: u64));
stub_fn!(glProgramUniform3ui64vARB, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform3ui64vNV, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform3uiEXT, (), (program: u32, location: i32, v0: u32, v1: u32, v2: u32));
stub_fn!(glProgramUniform3uiv, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform3uivEXT, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform4d, (), (program: u32, location: i32, v0: f64, v1: f64, v2: f64, v3: f64));
stub_fn!(glProgramUniform4dEXT, (), (program: u32, location: i32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glProgramUniform4dv, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform4dvEXT, (), (program: u32, location: i32, count: i32, value: *const f64));
stub_fn!(glProgramUniform4f, (), (program: u32, location: i32, v0: f32, v1: f32, v2: f32, v3: f32));
stub_fn!(glProgramUniform4fEXT, (), (program: u32, location: i32, v0: f32, v1: f32, v2: f32, v3: f32));
stub_fn!(glProgramUniform4fv, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform4fvEXT, (), (program: u32, location: i32, count: i32, value: *const f32));
stub_fn!(glProgramUniform4i, (), (program: u32, location: i32, v0: i32, v1: i32, v2: i32, v3: i32));
stub_fn!(glProgramUniform4i64ARB, (), (program: u32, location: i32, x: i64, y: i64, z: i64, w: i64));
stub_fn!(glProgramUniform4i64NV, (), (program: u32, location: i32, x: i64, y: i64, z: i64, w: i64));
stub_fn!(glProgramUniform4i64vARB, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform4i64vNV, (), (program: u32, location: i32, count: i32, value: *const i64));
stub_fn!(glProgramUniform4iEXT, (), (program: u32, location: i32, v0: i32, v1: i32, v2: i32, v3: i32));
stub_fn!(glProgramUniform4iv, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform4ivEXT, (), (program: u32, location: i32, count: i32, value: *const i32));
stub_fn!(glProgramUniform4ui, (), (program: u32, location: i32, v0: u32, v1: u32, v2: u32, v3: u32));
stub_fn!(glProgramUniform4ui64ARB, (), (program: u32, location: i32, x: u64, y: u64, z: u64, w: u64));
stub_fn!(glProgramUniform4ui64NV, (), (program: u32, location: i32, x: u64, y: u64, z: u64, w: u64));
stub_fn!(glProgramUniform4ui64vARB, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform4ui64vNV, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glProgramUniform4uiEXT, (), (program: u32, location: i32, v0: u32, v1: u32, v2: u32, v3: u32));
stub_fn!(glProgramUniform4uiv, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniform4uivEXT, (), (program: u32, location: i32, count: i32, value: *const u32));
stub_fn!(glProgramUniformHandleui64ARB, (), (program: u32, location: i32, value: u64));
stub_fn!(glProgramUniformHandleui64NV, (), (program: u32, location: i32, value: u64));
stub_fn!(glProgramUniformHandleui64vARB, (), (program: u32, location: i32, count: i32, values: *const u64));
stub_fn!(glProgramUniformHandleui64vNV, (), (program: u32, location: i32, count: i32, values: *const u64));
stub_fn!(glProgramUniformMatrix2dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix2fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix2x3dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2x3dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2x3fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix2x3fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix2x4dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2x4dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix2x4fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix2x4fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3x2dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3x2dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3x2fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3x2fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3x4dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3x4dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix3x4fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix3x4fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4x2dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4x2dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4x2fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4x2fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4x3dv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4x3dvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glProgramUniformMatrix4x3fv, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformMatrix4x3fvEXT, (), (program: u32, location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glProgramUniformui64NV, (), (program: u32, location: i32, value: u64));
stub_fn!(glProgramUniformui64vNV, (), (program: u32, location: i32, count: i32, value: *const u64));
stub_fn!(glPushAttrib, (), (mask: u32));
stub_fn!(glPushClientAttrib, (), (mask: u32));
stub_fn!(glPushClientAttribDefaultEXT, (), (mask: u32));
stub_fn!(glPushDebugGroup, (), (source: u32, id: u32, length: i32, message: *const std::ffi::c_char));
stub_fn!(glPushGroupMarkerEXT, (), (length: i32, marker: *const std::ffi::c_char));
stub_fn!(glRasterSamplesEXT, (), (samples: u32, fixedsamplelocations: u8));
stub_fn!(glReadnPixels, (), (x: i32, y: i32, width: i32, height: i32, format: u32, type_: u32, bufSize: i32, data: *mut std::ffi::c_void));
stub_fn!(glReadnPixelsARB, (), (x: i32, y: i32, width: i32, height: i32, format: u32, type_: u32, bufSize: i32, data: *mut std::ffi::c_void));
stub_fn!(glRenderMode, i32, (mode: u32));
stub_fn!(glRenderbufferStorageMultisampleAdvancedAMD, (), (target: u32, samples: i32, storageSamples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glRenderbufferStorageMultisampleCoverageNV, (), (target: u32, coverageSamples: i32, colorSamples: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glResetMemoryObjectParameterNV, (), (memory: u32, pname: u32));
stub_fn!(glResolveDepthValuesNV, (), ());
stub_fn!(glScissorArrayv, (), (first: u32, count: i32, v: *const i32));
stub_fn!(glScissorExclusiveArrayvNV, (), (first: u32, count: i32, v: *const i32));
stub_fn!(glScissorExclusiveNV, (), (x: i32, y: i32, width: i32, height: i32));
stub_fn!(glScissorIndexed, (), (index: u32, left: i32, bottom: i32, width: i32, height: i32));
stub_fn!(glScissorIndexedv, (), (index: u32, v: *const i32));
stub_fn!(glSecondaryColorP3ui, (), (type_: u32, color: u32));
stub_fn!(glSecondaryColorP3uiv, (), (type_: u32, color: *const u32));
stub_fn!(glSelectPerfMonitorCountersAMD, (), (monitor: u32, enable: u8, group: u32, numCounters: i32, counterList: *mut u32));
stub_fn!(glShadeModel, (), (mode: u32));
stub_fn!(glShaderBinary, (), (count: i32, shaders: *const u32, binaryFormat: u32, binary: *const std::ffi::c_void, length: i32));
stub_fn!(glShadingRateImageBarrierNV, (), (synchronize: u8));
stub_fn!(glShadingRateImagePaletteNV, (), (viewport: u32, first: u32, count: i32, rates: *const u32));
stub_fn!(glShadingRateSampleOrderCustomNV, (), (rate: u32, samples: u32, locations: *const i32));
stub_fn!(glShadingRateSampleOrderNV, (), (order: u32));
stub_fn!(glSignalVkFenceNV, (), (vkFence: u64));
stub_fn!(glSignalVkSemaphoreNV, (), (vkSemaphore: u64));
stub_fn!(glSpecializeShader, (), (shader: u32, pEntryPoint: *const std::ffi::c_char, numSpecializationConstants: u32, pConstantIndex: *const u32, pConstantValue: *const u32));
stub_fn!(glSpecializeShaderARB, (), (shader: u32, pEntryPoint: *const std::ffi::c_char, numSpecializationConstants: u32, pConstantIndex: *const u32, pConstantValue: *const u32));
stub_fn!(glStateCaptureNV, (), (state: u32, mode: u32));
stub_fn!(glStencilFillPathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, fillMode: u32, mask: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glStencilFillPathNV, (), (path: u32, fillMode: u32, mask: u32));
stub_fn!(glStencilStrokePathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, reference: i32, mask: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glStencilStrokePathNV, (), (path: u32, reference: i32, mask: u32));
stub_fn!(glStencilThenCoverFillPathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, fillMode: u32, mask: u32, coverMode: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glStencilThenCoverFillPathNV, (), (path: u32, fillMode: u32, mask: u32, coverMode: u32));
stub_fn!(glStencilThenCoverStrokePathInstancedNV, (), (numPaths: i32, pathNameType: u32, paths: *const std::ffi::c_void, pathBase: u32, reference: i32, mask: u32, coverMode: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glStencilThenCoverStrokePathNV, (), (path: u32, reference: i32, mask: u32, coverMode: u32));
stub_fn!(glSubpixelPrecisionBiasNV, (), (xbits: u32, ybits: u32));
stub_fn!(glTexAttachMemoryNV, (), (target: u32, memory: u32, offset: u64));
stub_fn!(glTexBufferARB, (), (target: u32, internalformat: u32, buffer: u32));
stub_fn!(glTexCoordP1ui, (), (type_: u32, coords: u32));
stub_fn!(glTexCoordP1uiv, (), (type_: u32, coords: *const u32));
stub_fn!(glTexCoordP2ui, (), (type_: u32, coords: u32));
stub_fn!(glTexCoordP2uiv, (), (type_: u32, coords: *const u32));
stub_fn!(glTexCoordP3ui, (), (type_: u32, coords: u32));
stub_fn!(glTexCoordP3uiv, (), (type_: u32, coords: *const u32));
stub_fn!(glTexCoordP4ui, (), (type_: u32, coords: u32));
stub_fn!(glTexCoordP4uiv, (), (type_: u32, coords: *const u32));
stub_fn!(glTexEnvf, (), (target: u32, pname: u32, param: f32));
stub_fn!(glTexEnvfv, (), (target: u32, pname: u32, params: *const f32));
stub_fn!(glTexEnvi, (), (target: u32, pname: u32, param: i32));
stub_fn!(glTexEnviv, (), (target: u32, pname: u32, params: *const i32));
stub_fn!(glTexImage1D, (), (target: u32, level: i32, internalformat: i32, width: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTexPageCommitmentARB, (), (target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, commit: u8));
stub_fn!(glTexPageCommitmentMemNV, (), (target: u32, layer: i32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, memory: u32, offset: u64, commit: u8));
stub_fn!(glTexParameterIiv, (), (target: u32, pname: u32, params: *const i32));
stub_fn!(glTexParameterIuiv, (), (target: u32, pname: u32, params: *const u32));
stub_fn!(glTexStorage1D, (), (target: u32, levels: i32, internalformat: u32, width: i32));
stub_fn!(glTexStorage1DEXT, (), (target: u32, levels: i32, internalformat: u32, width: i32));
stub_fn!(glTexStorage2DMultisample, (), (target: u32, samples: i32, internalformat: u32, width: i32, height: i32, fixedsamplelocations: u8));
stub_fn!(glTexStorage3DMultisample, (), (target: u32, samples: i32, internalformat: u32, width: i32, height: i32, depth: i32, fixedsamplelocations: u8));
stub_fn!(glTexSubImage1D, (), (target: u32, level: i32, xoffset: i32, width: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureAttachMemoryNV, (), (texture: u32, memory: u32, offset: u64));
stub_fn!(glTextureBarrier, (), ());
stub_fn!(glTextureBarrierNV, (), ());
stub_fn!(glTextureBuffer, (), (texture: u32, internalformat: u32, buffer: u32));
stub_fn!(glTextureBufferEXT, (), (texture: u32, target: u32, internalformat: u32, buffer: u32));
stub_fn!(glTextureBufferRange, (), (texture: u32, internalformat: u32, buffer: u32, offset: isize, size: isize));
stub_fn!(glTextureBufferRangeEXT, (), (texture: u32, target: u32, internalformat: u32, buffer: u32, offset: isize, size: isize));
stub_fn!(glTextureImage1DEXT, (), (texture: u32, target: u32, level: i32, internalformat: i32, width: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureImage2DEXT, (), (texture: u32, target: u32, level: i32, internalformat: i32, width: i32, height: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureImage3DEXT, (), (texture: u32, target: u32, level: i32, internalformat: i32, width: i32, height: i32, depth: i32, border: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTexturePageCommitmentEXT, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, commit: u8));
stub_fn!(glTexturePageCommitmentMemNV, (), (texture: u32, layer: i32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, memory: u32, offset: u64, commit: u8));
stub_fn!(glTextureParameterIiv, (), (texture: u32, pname: u32, params: *const i32));
stub_fn!(glTextureParameterIivEXT, (), (texture: u32, target: u32, pname: u32, params: *const i32));
stub_fn!(glTextureParameterIuiv, (), (texture: u32, pname: u32, params: *const u32));
stub_fn!(glTextureParameterIuivEXT, (), (texture: u32, target: u32, pname: u32, params: *const u32));
stub_fn!(glTextureParameterf, (), (texture: u32, pname: u32, param: f32));
stub_fn!(glTextureParameterfEXT, (), (texture: u32, target: u32, pname: u32, param: f32));
stub_fn!(glTextureParameterfv, (), (texture: u32, pname: u32, param: *const f32));
stub_fn!(glTextureParameterfvEXT, (), (texture: u32, target: u32, pname: u32, params: *const f32));
stub_fn!(glTextureParameteri, (), (texture: u32, pname: u32, param: i32));
stub_fn!(glTextureParameteriEXT, (), (texture: u32, target: u32, pname: u32, param: i32));
stub_fn!(glTextureParameteriv, (), (texture: u32, pname: u32, param: *const i32));
stub_fn!(glTextureParameterivEXT, (), (texture: u32, target: u32, pname: u32, params: *const i32));
stub_fn!(glTextureRenderbufferEXT, (), (texture: u32, target: u32, renderbuffer: u32));
stub_fn!(glTextureStorage1D, (), (texture: u32, levels: i32, internalformat: u32, width: i32));
stub_fn!(glTextureStorage1DEXT, (), (texture: u32, target: u32, levels: i32, internalformat: u32, width: i32));
stub_fn!(glTextureStorage2D, (), (texture: u32, levels: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glTextureStorage2DEXT, (), (texture: u32, target: u32, levels: i32, internalformat: u32, width: i32, height: i32));
stub_fn!(glTextureStorage2DMultisample, (), (texture: u32, samples: i32, internalformat: u32, width: i32, height: i32, fixedsamplelocations: u8));
stub_fn!(glTextureStorage2DMultisampleEXT, (), (texture: u32, target: u32, samples: i32, internalformat: u32, width: i32, height: i32, fixedsamplelocations: u8));
stub_fn!(glTextureStorage3D, (), (texture: u32, levels: i32, internalformat: u32, width: i32, height: i32, depth: i32));
stub_fn!(glTextureStorage3DEXT, (), (texture: u32, target: u32, levels: i32, internalformat: u32, width: i32, height: i32, depth: i32));
stub_fn!(glTextureStorage3DMultisample, (), (texture: u32, samples: i32, internalformat: u32, width: i32, height: i32, depth: i32, fixedsamplelocations: u8));
stub_fn!(glTextureStorage3DMultisampleEXT, (), (texture: u32, target: u32, samples: i32, internalformat: u32, width: i32, height: i32, depth: i32, fixedsamplelocations: u8));
stub_fn!(glTextureSubImage1D, (), (texture: u32, level: i32, xoffset: i32, width: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureSubImage1DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, width: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureSubImage2D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureSubImage2DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, width: i32, height: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureSubImage3D, (), (texture: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureSubImage3DEXT, (), (texture: u32, target: u32, level: i32, xoffset: i32, yoffset: i32, zoffset: i32, width: i32, height: i32, depth: i32, format: u32, type_: u32, pixels: *const std::ffi::c_void));
stub_fn!(glTextureView, (), (texture: u32, target: u32, origtexture: u32, internalformat: u32, minlevel: u32, numlevels: u32, minlayer: u32, numlayers: u32));
stub_fn!(glTransformPathNV, (), (resultPath: u32, srcPath: u32, transformType: u32, transformValues: *const f32));
stub_fn!(glUniform1d, (), (location: i32, x: f64));
stub_fn!(glUniform1dv, (), (location: i32, count: i32, value: *const f64));
stub_fn!(glUniform1i64ARB, (), (location: i32, x: i64));
stub_fn!(glUniform1i64NV, (), (location: i32, x: i64));
stub_fn!(glUniform1i64vARB, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform1i64vNV, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform1ui64ARB, (), (location: i32, x: u64));
stub_fn!(glUniform1ui64NV, (), (location: i32, x: u64));
stub_fn!(glUniform1ui64vARB, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform1ui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform2d, (), (location: i32, x: f64, y: f64));
stub_fn!(glUniform2dv, (), (location: i32, count: i32, value: *const f64));
stub_fn!(glUniform2i64ARB, (), (location: i32, x: i64, y: i64));
stub_fn!(glUniform2i64NV, (), (location: i32, x: i64, y: i64));
stub_fn!(glUniform2i64vARB, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform2i64vNV, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform2ui64ARB, (), (location: i32, x: u64, y: u64));
stub_fn!(glUniform2ui64NV, (), (location: i32, x: u64, y: u64));
stub_fn!(glUniform2ui64vARB, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform2ui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform3d, (), (location: i32, x: f64, y: f64, z: f64));
stub_fn!(glUniform3dv, (), (location: i32, count: i32, value: *const f64));
stub_fn!(glUniform3i64ARB, (), (location: i32, x: i64, y: i64, z: i64));
stub_fn!(glUniform3i64NV, (), (location: i32, x: i64, y: i64, z: i64));
stub_fn!(glUniform3i64vARB, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform3i64vNV, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform3ui64ARB, (), (location: i32, x: u64, y: u64, z: u64));
stub_fn!(glUniform3ui64NV, (), (location: i32, x: u64, y: u64, z: u64));
stub_fn!(glUniform3ui64vARB, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform3ui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform4d, (), (location: i32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glUniform4dv, (), (location: i32, count: i32, value: *const f64));
stub_fn!(glUniform4i64ARB, (), (location: i32, x: i64, y: i64, z: i64, w: i64));
stub_fn!(glUniform4i64NV, (), (location: i32, x: i64, y: i64, z: i64, w: i64));
stub_fn!(glUniform4i64vARB, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform4i64vNV, (), (location: i32, count: i32, value: *const i64));
stub_fn!(glUniform4ui64ARB, (), (location: i32, x: u64, y: u64, z: u64, w: u64));
stub_fn!(glUniform4ui64NV, (), (location: i32, x: u64, y: u64, z: u64, w: u64));
stub_fn!(glUniform4ui64vARB, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniform4ui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniformHandleui64ARB, (), (location: i32, value: u64));
stub_fn!(glUniformHandleui64NV, (), (location: i32, value: u64));
stub_fn!(glUniformHandleui64vARB, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniformHandleui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUniformMatrix2dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix2x3dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix2x3fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformMatrix2x4dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix2x4fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformMatrix3dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix3x2dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix3x2fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformMatrix3x4dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix3x4fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformMatrix4dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix4x2dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix4x2fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformMatrix4x3dv, (), (location: i32, count: i32, transpose: u8, value: *const f64));
stub_fn!(glUniformMatrix4x3fv, (), (location: i32, count: i32, transpose: u8, value: *const f32));
stub_fn!(glUniformSubroutinesuiv, (), (shadertype: u32, count: i32, indices: *const u32));
stub_fn!(glUniformui64NV, (), (location: i32, value: u64));
stub_fn!(glUniformui64vNV, (), (location: i32, count: i32, value: *const u64));
stub_fn!(glUnmapNamedBuffer, u8, (buffer: u32));
stub_fn!(glUnmapNamedBufferEXT, u8, (buffer: u32));
stub_fn!(glUseProgramStages, (), (pipeline: u32, stages: u32, program: u32));
stub_fn!(glUseShaderProgramEXT, (), (type_: u32, program: u32));
stub_fn!(glValidateProgramPipeline, (), (pipeline: u32));
stub_fn!(glVertexArrayAttribBinding, (), (vaobj: u32, attribindex: u32, bindingindex: u32));
stub_fn!(glVertexArrayAttribFormat, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, normalized: u8, relativeoffset: u32));
stub_fn!(glVertexArrayAttribIFormat, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, relativeoffset: u32));
stub_fn!(glVertexArrayAttribLFormat, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, relativeoffset: u32));
stub_fn!(glVertexArrayBindVertexBufferEXT, (), (vaobj: u32, bindingindex: u32, buffer: u32, offset: isize, stride: i32));
stub_fn!(glVertexArrayBindingDivisor, (), (vaobj: u32, bindingindex: u32, divisor: u32));
stub_fn!(glVertexArrayColorOffsetEXT, (), (vaobj: u32, buffer: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayEdgeFlagOffsetEXT, (), (vaobj: u32, buffer: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayElementBuffer, (), (vaobj: u32, buffer: u32));
stub_fn!(glVertexArrayFogCoordOffsetEXT, (), (vaobj: u32, buffer: u32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayIndexOffsetEXT, (), (vaobj: u32, buffer: u32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayMultiTexCoordOffsetEXT, (), (vaobj: u32, buffer: u32, texunit: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayNormalOffsetEXT, (), (vaobj: u32, buffer: u32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayParameteriAPPLE, (), (pname: u32, param: i32));
stub_fn!(glVertexArrayRangeAPPLE, (), (length: i32, pointer: *mut std::ffi::c_void));
stub_fn!(glVertexArrayRangeNV, (), (length: i32, pointer: *const std::ffi::c_void));
stub_fn!(glVertexArraySecondaryColorOffsetEXT, (), (vaobj: u32, buffer: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayTexCoordOffsetEXT, (), (vaobj: u32, buffer: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayVertexAttribBindingEXT, (), (vaobj: u32, attribindex: u32, bindingindex: u32));
stub_fn!(glVertexArrayVertexAttribDivisorEXT, (), (vaobj: u32, index: u32, divisor: u32));
stub_fn!(glVertexArrayVertexAttribFormatEXT, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, normalized: u8, relativeoffset: u32));
stub_fn!(glVertexArrayVertexAttribIFormatEXT, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, relativeoffset: u32));
stub_fn!(glVertexArrayVertexAttribIOffsetEXT, (), (vaobj: u32, buffer: u32, index: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayVertexAttribLFormatEXT, (), (vaobj: u32, attribindex: u32, size: i32, type_: u32, relativeoffset: u32));
stub_fn!(glVertexArrayVertexAttribLOffsetEXT, (), (vaobj: u32, buffer: u32, index: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexArrayVertexAttribOffsetEXT, (), (vaobj: u32, buffer: u32, index: u32, size: i32, type_: u32, normalized: u8, stride: i32, offset: isize));
stub_fn!(glVertexArrayVertexBindingDivisorEXT, (), (vaobj: u32, bindingindex: u32, divisor: u32));
stub_fn!(glVertexArrayVertexBuffer, (), (vaobj: u32, bindingindex: u32, buffer: u32, offset: isize, stride: i32));
stub_fn!(glVertexArrayVertexBuffers, (), (vaobj: u32, first: u32, count: i32, buffers: *const u32, offsets: *const isize, strides: *const i32));
stub_fn!(glVertexArrayVertexOffsetEXT, (), (vaobj: u32, buffer: u32, size: i32, type_: u32, stride: i32, offset: isize));
stub_fn!(glVertexAttrib1dARB, (), (index: u32, x: f64));
stub_fn!(glVertexAttrib1dNV, (), (index: u32, x: f64));
stub_fn!(glVertexAttrib1dvARB, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib1dvNV, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib1fNV, (), (index: u32, x: f32));
stub_fn!(glVertexAttrib1fvNV, (), (index: u32, v: *const f32));
stub_fn!(glVertexAttrib1hNV, (), (index: u32, x: u16));
stub_fn!(glVertexAttrib1hvNV, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttrib1sARB, (), (index: u32, x: i16));
stub_fn!(glVertexAttrib1sNV, (), (index: u32, x: i16));
stub_fn!(glVertexAttrib1svARB, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib1svNV, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib2dARB, (), (index: u32, x: f64, y: f64));
stub_fn!(glVertexAttrib2dNV, (), (index: u32, x: f64, y: f64));
stub_fn!(glVertexAttrib2dvARB, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib2dvNV, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib2fNV, (), (index: u32, x: f32, y: f32));
stub_fn!(glVertexAttrib2fvNV, (), (index: u32, v: *const f32));
stub_fn!(glVertexAttrib2hNV, (), (index: u32, x: u16, y: u16));
stub_fn!(glVertexAttrib2hvNV, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttrib2sARB, (), (index: u32, x: i16, y: i16));
stub_fn!(glVertexAttrib2sNV, (), (index: u32, x: i16, y: i16));
stub_fn!(glVertexAttrib2svARB, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib2svNV, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib3dARB, (), (index: u32, x: f64, y: f64, z: f64));
stub_fn!(glVertexAttrib3dNV, (), (index: u32, x: f64, y: f64, z: f64));
stub_fn!(glVertexAttrib3dvARB, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib3dvNV, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib3fNV, (), (index: u32, x: f32, y: f32, z: f32));
stub_fn!(glVertexAttrib3fvNV, (), (index: u32, v: *const f32));
stub_fn!(glVertexAttrib3hNV, (), (index: u32, x: u16, y: u16, z: u16));
stub_fn!(glVertexAttrib3hvNV, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttrib3sARB, (), (index: u32, x: i16, y: i16, z: i16));
stub_fn!(glVertexAttrib3sNV, (), (index: u32, x: i16, y: i16, z: i16));
stub_fn!(glVertexAttrib3svARB, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib3svNV, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib4NbvARB, (), (index: u32, v: *const i8));
stub_fn!(glVertexAttrib4NivARB, (), (index: u32, v: *const i32));
stub_fn!(glVertexAttrib4NsvARB, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib4NubARB, (), (index: u32, x: u8, y: u8, z: u8, w: u8));
stub_fn!(glVertexAttrib4NubvARB, (), (index: u32, v: *const u8));
stub_fn!(glVertexAttrib4NuivARB, (), (index: u32, v: *const u32));
stub_fn!(glVertexAttrib4NusvARB, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttrib4bvARB, (), (index: u32, v: *const i8));
stub_fn!(glVertexAttrib4dARB, (), (index: u32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glVertexAttrib4dNV, (), (index: u32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glVertexAttrib4dvARB, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib4dvNV, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttrib4fNV, (), (index: u32, x: f32, y: f32, z: f32, w: f32));
stub_fn!(glVertexAttrib4fvNV, (), (index: u32, v: *const f32));
stub_fn!(glVertexAttrib4hNV, (), (index: u32, x: u16, y: u16, z: u16, w: u16));
stub_fn!(glVertexAttrib4hvNV, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttrib4ivARB, (), (index: u32, v: *const i32));
stub_fn!(glVertexAttrib4sARB, (), (index: u32, x: i16, y: i16, z: i16, w: i16));
stub_fn!(glVertexAttrib4sNV, (), (index: u32, x: i16, y: i16, z: i16, w: i16));
stub_fn!(glVertexAttrib4svARB, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib4svNV, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttrib4ubNV, (), (index: u32, x: u8, y: u8, z: u8, w: u8));
stub_fn!(glVertexAttrib4ubvARB, (), (index: u32, v: *const u8));
stub_fn!(glVertexAttrib4ubvNV, (), (index: u32, v: *const u8));
stub_fn!(glVertexAttrib4uivARB, (), (index: u32, v: *const u32));
stub_fn!(glVertexAttrib4usvARB, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttribArrayObjectATI, (), (index: u32, size: i32, type_: u32, normalized: u8, stride: i32, buffer: u32, offset: u32));
stub_fn!(glVertexAttribFormatNV, (), (index: u32, size: i32, type_: u32, normalized: u8, stride: i32));
stub_fn!(glVertexAttribI1iEXT, (), (index: u32, x: i32));
stub_fn!(glVertexAttribI1ivEXT, (), (index: u32, v: *const i32));
stub_fn!(glVertexAttribI1uiEXT, (), (index: u32, x: u32));
stub_fn!(glVertexAttribI1uivEXT, (), (index: u32, v: *const u32));
stub_fn!(glVertexAttribI2iEXT, (), (index: u32, x: i32, y: i32));
stub_fn!(glVertexAttribI2ivEXT, (), (index: u32, v: *const i32));
stub_fn!(glVertexAttribI2uiEXT, (), (index: u32, x: u32, y: u32));
stub_fn!(glVertexAttribI2uivEXT, (), (index: u32, v: *const u32));
stub_fn!(glVertexAttribI3iEXT, (), (index: u32, x: i32, y: i32, z: i32));
stub_fn!(glVertexAttribI3ivEXT, (), (index: u32, v: *const i32));
stub_fn!(glVertexAttribI3uiEXT, (), (index: u32, x: u32, y: u32, z: u32));
stub_fn!(glVertexAttribI3uivEXT, (), (index: u32, v: *const u32));
stub_fn!(glVertexAttribI4bvEXT, (), (index: u32, v: *const i8));
stub_fn!(glVertexAttribI4svEXT, (), (index: u32, v: *const i16));
stub_fn!(glVertexAttribI4ubvEXT, (), (index: u32, v: *const u8));
stub_fn!(glVertexAttribI4usvEXT, (), (index: u32, v: *const u16));
stub_fn!(glVertexAttribIFormatNV, (), (index: u32, size: i32, type_: u32, stride: i32));
stub_fn!(glVertexAttribL1d, (), (index: u32, x: f64));
stub_fn!(glVertexAttribL1dEXT, (), (index: u32, x: f64));
stub_fn!(glVertexAttribL1dv, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL1dvEXT, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL1i64NV, (), (index: u32, x: i64));
stub_fn!(glVertexAttribL1i64vNV, (), (index: u32, v: *const i64));
stub_fn!(glVertexAttribL1ui64ARB, (), (index: u32, x: u64));
stub_fn!(glVertexAttribL1ui64NV, (), (index: u32, x: u64));
stub_fn!(glVertexAttribL1ui64vARB, (), (index: u32, v: *const u64));
stub_fn!(glVertexAttribL1ui64vNV, (), (index: u32, v: *const u64));
stub_fn!(glVertexAttribL2d, (), (index: u32, x: f64, y: f64));
stub_fn!(glVertexAttribL2dEXT, (), (index: u32, x: f64, y: f64));
stub_fn!(glVertexAttribL2dv, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL2dvEXT, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL2i64NV, (), (index: u32, x: i64, y: i64));
stub_fn!(glVertexAttribL2i64vNV, (), (index: u32, v: *const i64));
stub_fn!(glVertexAttribL2ui64NV, (), (index: u32, x: u64, y: u64));
stub_fn!(glVertexAttribL2ui64vNV, (), (index: u32, v: *const u64));
stub_fn!(glVertexAttribL3d, (), (index: u32, x: f64, y: f64, z: f64));
stub_fn!(glVertexAttribL3dEXT, (), (index: u32, x: f64, y: f64, z: f64));
stub_fn!(glVertexAttribL3dv, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL3dvEXT, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL3i64NV, (), (index: u32, x: i64, y: i64, z: i64));
stub_fn!(glVertexAttribL3i64vNV, (), (index: u32, v: *const i64));
stub_fn!(glVertexAttribL3ui64NV, (), (index: u32, x: u64, y: u64, z: u64));
stub_fn!(glVertexAttribL3ui64vNV, (), (index: u32, v: *const u64));
stub_fn!(glVertexAttribL4d, (), (index: u32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glVertexAttribL4dEXT, (), (index: u32, x: f64, y: f64, z: f64, w: f64));
stub_fn!(glVertexAttribL4dv, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL4dvEXT, (), (index: u32, v: *const f64));
stub_fn!(glVertexAttribL4i64NV, (), (index: u32, x: i64, y: i64, z: i64, w: i64));
stub_fn!(glVertexAttribL4i64vNV, (), (index: u32, v: *const i64));
stub_fn!(glVertexAttribL4ui64NV, (), (index: u32, x: u64, y: u64, z: u64, w: u64));
stub_fn!(glVertexAttribL4ui64vNV, (), (index: u32, v: *const u64));
stub_fn!(glVertexAttribLFormat, (), (attribindex: u32, size: i32, type_: u32, relativeoffset: u32));
stub_fn!(glVertexAttribLFormatNV, (), (index: u32, size: i32, type_: u32, stride: i32));
stub_fn!(glVertexAttribLPointer, (), (index: u32, size: i32, type_: u32, stride: i32, pointer: *const std::ffi::c_void));
stub_fn!(glVertexAttribLPointerEXT, (), (index: u32, size: i32, type_: u32, stride: i32, pointer: *const std::ffi::c_void));
stub_fn!(glVertexAttribParameteriAMD, (), (index: u32, pname: u32, param: i32));
stub_fn!(glVertexAttribPointerNV, (), (index: u32, fsize: i32, type_: u32, stride: i32, pointer: *const std::ffi::c_void));
stub_fn!(glVertexAttribs1dvNV, (), (index: u32, count: i32, v: *const f64));
stub_fn!(glVertexAttribs1fvNV, (), (index: u32, count: i32, v: *const f32));
stub_fn!(glVertexAttribs1hvNV, (), (index: u32, n: i32, v: *const u16));
stub_fn!(glVertexAttribs1svNV, (), (index: u32, count: i32, v: *const i16));
stub_fn!(glVertexAttribs2dvNV, (), (index: u32, count: i32, v: *const f64));
stub_fn!(glVertexAttribs2fvNV, (), (index: u32, count: i32, v: *const f32));
stub_fn!(glVertexAttribs2hvNV, (), (index: u32, n: i32, v: *const u16));
stub_fn!(glVertexAttribs2svNV, (), (index: u32, count: i32, v: *const i16));
stub_fn!(glVertexAttribs3dvNV, (), (index: u32, count: i32, v: *const f64));
stub_fn!(glVertexAttribs3fvNV, (), (index: u32, count: i32, v: *const f32));
stub_fn!(glVertexAttribs3hvNV, (), (index: u32, n: i32, v: *const u16));
stub_fn!(glVertexAttribs3svNV, (), (index: u32, count: i32, v: *const i16));
stub_fn!(glVertexAttribs4dvNV, (), (index: u32, count: i32, v: *const f64));
stub_fn!(glVertexAttribs4fvNV, (), (index: u32, count: i32, v: *const f32));
stub_fn!(glVertexAttribs4hvNV, (), (index: u32, n: i32, v: *const u16));
stub_fn!(glVertexAttribs4svNV, (), (index: u32, count: i32, v: *const i16));
stub_fn!(glVertexAttribs4ubvNV, (), (index: u32, count: i32, v: *const u8));
stub_fn!(glVertexBindingDivisor, (), (bindingindex: u32, divisor: u32));
stub_fn!(glVertexP2ui, (), (type_: u32, value: u32));
stub_fn!(glVertexP2uiv, (), (type_: u32, value: *const u32));
stub_fn!(glVertexP3ui, (), (type_: u32, value: u32));
stub_fn!(glVertexP3uiv, (), (type_: u32, value: *const u32));
stub_fn!(glVertexP4ui, (), (type_: u32, value: u32));
stub_fn!(glVertexP4uiv, (), (type_: u32, value: *const u32));
stub_fn!(glViewportArrayv, (), (first: u32, count: i32, v: *const f32));
stub_fn!(glViewportIndexedf, (), (index: u32, x: f32, y: f32, w: f32, h: f32));
stub_fn!(glViewportIndexedfv, (), (index: u32, v: *const f32));
stub_fn!(glViewportPositionWScaleNV, (), (index: u32, xcoeff: f32, ycoeff: f32));
stub_fn!(glViewportSwizzleNV, (), (index: u32, swizzlex: u32, swizzley: u32, swizzlez: u32, swizzlew: u32));
stub_fn!(glWaitVkSemaphoreNV, (), (vkSemaphore: u64));
stub_fn!(glWeightPathsNV, (), (resultPath: u32, numPaths: i32, paths: *const u32, weights: *const f32));
stub_fn!(glWindowRectanglesEXT, (), (mode: u32, count: i32, box_: *const i32));
passthrough_alias!(glBufferStorageEXT, crate::gl::buffer::glBufferStorage, (), (target: u32, size: isize, data: *const std::ffi::c_void, flags: u32));
passthrough_alias!(glMultiDrawArraysIndirectEXT, crate::gl::multi_draw::glMultiDrawArraysIndirect, (), (mode: u32, indirect: *const std::ffi::c_void, drawcount: i32, stride: i32));
passthrough_alias!(glMultiDrawElementsBaseVertexEXT, crate::gl::multi_draw::glMultiDrawElementsBaseVertex, (), (mode: u32, count: *const i32, type_: u32, indices: *const *const std::ffi::c_void, drawcount: i32, basevertex: *const i32));
passthrough_alias!(glMultiDrawElementsIndirectEXT, crate::gl::multi_draw::glMultiDrawElementsIndirect, (), (mode: u32, type_: u32, indirect: *const std::ffi::c_void, drawcount: i32, stride: i32));
passthrough_alias!(glTexStorage2DEXT, crate::gl::texture::glTexStorage2D, (), (target: u32, levels: i32, internalformat: u32, width: i32, height: i32));
passthrough_alias!(glTexStorage3DEXT, crate::gl::texture::glTexStorage3D, (), (target: u32, levels: i32, internalformat: u32, width: i32, height: i32, depth: i32));

#[allow(dead_code)]
pub const STUB_COUNT: usize = 1000;
#[allow(dead_code)]
pub const ALIAS_COUNT: usize = 6;
